[theme]
base = "light"
primaryColor = "#6ba368"
backgroundColor = "#fcf9f0"
secondaryBackgroundColor = "#f5efe0"
textColor = "#43413a"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
